controller_list:
  - name: "arm_controller"
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: [robot_arm_elbow_joint, robot_arm_shoulder_lift_joint, robot_arm_shoulder_pan_joint,
    robot_arm_wrist_1_joint, robot_arm_wrist_2_joint, robot_arm_wrist_3_joint]
  - name: gripper_controller
    action_ns: gripper_cmd
    type: GripperCommand
    joints:
     - robot_egh_gripper_finger_left_joint

