controller_list:
  - name: fake_ur5_arm_controller
    joints:
      - robot_arm_shoulder_pan_joint
      - robot_arm_shoulder_lift_joint
      - robot_arm_elbow_joint
      - robot_arm_wrist_1_joint
      - robot_arm_wrist_2_joint
      - robot_arm_wrist_3_joint
  - name: fake_egh_gripper_controller
    joints:
      - robot_egh_gripper_finger_left_joint
      - robot_egh_gripper_finger_right_joint