controller_list:
  - name: "arm_controller"
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: [robot_ur10_elbow_joint, robot_ur10_shoulder_lift_joint, robot_ur10_shoulder_pan_joint,
    robot_ur10_wrist_1_joint, robot_ur10_wrist_2_joint, robot_ur10_wrist_3_joint]
